export const ADD_PRODUCTS_INFO = "ADD_PRODUCTS_INFO";
export const LOGIN_USER = "LOGIN_USER";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SET_FILTERED_PRODUCTS_LIST = "SET_FILTERED_PRODUCTS_LIST";
