export const products = [
  {
    id: 1,
    name: "Alligator",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJc5ok_qHjIrP6pUw8tZBiVJaoH2w0MxwQXA&usqp=CAU",
    description: "figura 3d impresa en resina de un cocodrilo",
    size: "m",
    price: 12000,
    stock: 10,
    materialName: "ABS",
    categoryName: "accesorio",
    reviews: "Muy buen producto",
    averageScore: 5,
  },
  {
    id: 2,
    name: "Guerrero demonio",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdjx09XzY-Khv7pyCZpVHbLQw53MC7amn5JQ&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "s",
    price: 12000,
    stock: 10,
    materialName: "ABS",
    categoryName: "accesorio",
    reviews: "Muy buen producto",
    averageScore: 5,
  },
  {
    id: 3,
    name: "Sailor girl",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDrIlORwKfpTe0HatjEC62MzWn4vRU4icOdg&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "m",
    price: 12000,
    stock: 10,
    materialName: "ABS",
    categoryName: "accesorio",
    reviews: "Muy buen producto",
    averageScore: 5,
  },
  {
    id: 4,
    name: "Alien",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrOeFndtQ9f6Lm5pZigNJasLs8DgCrmvORPbeI-CuWg03o6U-OoR3N8GsL32XEl0I5PHw&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "m",
    price: 12000,
    stock: 10,
    materialName: "ABS",
    categoryName: "accesorio",
    reviews: "Muy mal producto",
    averageScore: 3,
  },
  {
    name: "Galactic Armory",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKXeiFhdI3IfQoc7vwmutwZ8oMzHg1FgGhxg&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "m",
    price: 12000,
    stock: 10,
    materialName: "ABS",
    categoryName: "accesorio",
  },
  {
    name: "Demon Slayer - Zenitsu",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4Hz6CkNgA3hToQ7bGGC73okk96y9VUrF-eA&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "s",
    price: 12000,
    stock: 10,
    materialName: "ABS",
    categoryName: "accesorio",
  },
  {
    name: "Fire Emblem",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNdhCZbqLqRpj2s-ZMEb3KDZ_kWCF4apwOSmXYKi_7c93qtD6jB7YPPPunMKj2p29fZ6k&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "s",
    price: 12000,
    stock: 10,
    materialName: "ABS",
    categoryName: "accesorio",
  },
  {
    name: "Yanfei",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNwTe7UaDvDGlwiewTATTJdC3BdTo0xIfSBA&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "l",
    price: 12000,
    stock: 10,
    materialName: "ABS",
    categoryName: "accesorio",
  },
  {
    name: "Whitebeard",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAEOLCnW54jOAn7nOkkz3emHONXLKQwZ56qQ&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "x",
    price: 12000,
    stock: 10,
    materialName: "ABS",
    categoryName: "accesorio",
  },
  {
    name: "The Mandalorian",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWFyEvM9alFl-v83JjCh4Y26Na3VFLHXGXrg&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "l", // Tienes un valor vacío, puedes llenarlo con el valor deseado
    price: 12000,
    stock: 10,
    materialName: "ABS",
    categoryName: "accesorio",
  },
  {
    name: "Alligator",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJc5ok_qHjIrP6pUw8tZBiVJaoH2w0MxwQXA&usqp=CAU",
    description: "figura 3d impresa en resina de un cocodrilo",
    size: "s",
    price: 12000,
    stock: 10,
    materialName: "ABS",
    categoryName: "accesorio",
  },
  {
    name: "Guerrero demonio",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdjx09XzY-Khv7pyCZpVHbLQw53MC7amn5JQ&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "s",
    price: 12000,
    stock: 10,
    materialName: "ABS",
    categoryName: "accesorio",
  },
  {
    name: "Sailor girl",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDrIlORwKfpTe0HatjEC62MzWn4vRU4icOdg&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "m",
    price: 12000,
    stock: 10,
    materialName: "ABS",
    categoryName: "accesorio",
  },
  {
    name: "Alien",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrOeFndtQ9f6Lm5pZigNJasLs8DgCrmvORPbeI-CuWg03o6U-OoR3N8GsL32XEl0I5PHw&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "s",
    price: 12000,
    stock: 10,
    materialName: "ABS",
    categoryName: "accesorio",
    countReviews: 5,
    averageScore: 5,
  },
  {
    name: "Galactic Armory",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKXeiFhdI3IfQoc7vwmutwZ8oMzHg1FgGhxg&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "m",
    price: 12000,
    stock: 10,
    materialName: "PLA",
    categoryName: "decoracion",
    countReviews: 5,
    averageScore: 5,
  },
  {
    name: "Demon Slayer - Zenitsu",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4Hz6CkNgA3hToQ7bGGC73okk96y9VUrF-eA&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "s",
    price: 12000,
    stock: 10,
    materialName: "PLA",
    categoryName: "decoracion",
    countReviews: 5,
    averageScore: 5,
  },
  {
    name: "Fire Emblem",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNdhCZbqLqRpj2s-ZMEb3KDZ_kWCF4apwOSmXYKi_7c93qtD6jB7YPPPunMKj2p29fZ6k&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "s",
    price: 12000,
    stock: 10,
    materialName: "PLA",
    categoryName: "decoracion",
    countReviews: 5,
    averageScore: 5,
  },
  {
    name: "Yanfei",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNwTe7UaDvDGlwiewTATTJdC3BdTo0xIfSBA&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "l",
    price: 12000,
    stock: 10,
    materialName: "PLA",
    categoryName: "decoracion",

  },
  {
    name: "Whitebeard",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAEOLCnW54jOAn7nOkkz3emHONXLKQwZ56qQ&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "x",
    price: 12000,
    stock: 10,
    materialName: "ABS",
    categoryName: "accesorio",
    countReviews: 5,
    averageScore: 5,
  },
  {
    name: "The Mandalorian",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWFyEvM9alFl-v83JjCh4Y26Na3VFLHXGXrg&usqp=CAU",
    description: "figura 3d impresa en resina",
    size: "l", // Tienes un valor vacío, puedes llenarlo con el valor deseado
    price: 12000,
    stock: 10,
    materialName: "ABS",
    categoryName: "accesorio",
  },
];

